routes:
  /:
    controller: channel
    data: page.home
    template:
      - home

collections:
  /blog/:
    permalink: /posts/{slug}/
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/